### ISSUE TITLE
I need comments in English

### ISSUE THREAD

**Issue by goldhillpaladin** [pixie-grasper/ruby-fonttool#1]
Can you write comments in English？

**Comment by pixie-grasper** [comment]
I will try to write comments in English from now. Please wait me.

**Comment by pixie-grasper** [comment]
I have tried to write comments.
Could you please read the latest and comment to me?

**Comment by goldhillpaladin** [comment]
thank you for your update. it help me.

**Comment by goldhillpaladin** [comment]
Ask another question. Dou you know how to show the image of one glyph after extracting the charstring of glyphs from cff?

**Comment by pixie-grasper** [comment]
I do not know exactly.
I think how to show depends on the environment, not depends on the CFF.

Exempli gratia;
1. The cairo rasterizes glyphs what you want to show and sends rasterized image by the Wayland.
2. Graphic cards output signals to the VGA-connector to show on the monitor.
3. Now you will see the glyphs on the monitor.

**Comment by goldhillpaladin** [comment]
You know, glyphs in a cff is described by Type 2 charstrings.
Below is the charstring of a glyph that I extracted from a cff.

153 67 76 60 83 62 213 65 hstemhm 170 77 112 93 15 74 226 78 cntrmask -127 -356 -95 560 rmoveto -13 37 -12 39 -7 31 -78 -20 rcurveline 16 -34 8 -31 6 -45 rrcurveto 399 104 rmoveto -88 36 -9 -39 -11 -27 -26 -52 rlinecurve 76 -26 31 71 7 13 20 24 rlinecurve hintmask cntrmask -275 -679 rmoveto -5 42 -10 56 -9 45 -86 -21 rcurveline 14 -38 8 -56 -9 -44 rrcurveto 315 24 rmoveto -13 43 -14 50 -11 41 -81 -17 rcurveline 13 -36 15 -64 1 -41 rrcurveto -350 147 rmoveto -80 28 -15 -54 -30 -51 -37 -39 rlinecurve 87 -40 25 37 36 80 14 39 rlinecurve 686 -119 rmoveto -30 46 -35 57 -24 44 -77 -31 rcurveline 27 -45 31 -62 14 -44 rrcurveto hintmask -359 34 775 rmoveto 226 -213 -226 hlineto -74 hmoveto -220 213 220 hlineto 74 -418 rmoveto 129 97 -2 -5 74 hvcurveto 74 vlineto -5 -74 -97 -2 -129 hhcurveto 83 vlineto 141 93 -2 -5 77 hvcurveto -5 42 -2 56 79 vvcurveto 67 2 68 5 42 vhcurveto -5 -83 -101 -2 -160 hhcurveto -160 -102 2 5 -83 hvcurveto 5 -42 2 -68 -67 vvcurveto -67 -2 -68 -5 -42 vhcurveto 5 76 91 2 137 hhcurveto -83 vlineto -133 -97 2 5 -77 hvcurveto -74 vlineto 5 76 98 2 133 hhcurveto -76 vlineto -169 -127 2 5 -96 hvcurveto -81 vlineto 4 102 138 3 187 hhcurveto 186 139 -2 -4 102 hvcurveto 80 vlineto -5 -95 -126 -2 -167 hhcurveto endchar 

As we know, a CFF font rasterizer(e.g. Adobe CFF font rasterizer) use a sequence of operand-operator such as above to draw the outline of a glyph. After filling the outline, we get the graphics of a glyph on the screen.

My question is how to interpret the charstring. Or do you know any library which is able to do it?

**Comment by pixie-grasper** [comment]
I am sorry for my misunderstanding that how to _show_.
Commands in a charstring is interpreted like as PostScript Notation (aka Reverse Polish Notation).

Let us see the Technical Note #5177 ''The Type 2 Charstring Format''.
Section 3.1 ''Type 2 Charstring Organization'' says Type 2 charstring program may be represented as
`w? {hs* vs* cm* hm* mt subpath}? {mt subpath}* endchar`
The `w` indicates width, `endchar` and two-character-sequence indicates special commands, and `subpath` is the other commands.

Exempli gratia;
Your charstring begin with `153 67 76 60 83 62 213 65 hstemhm` and `hstemhm` requires even arguments, so the `w` is omitted in this charstring.
The `hstemhm` command (and also `cntrmask` command) does not effect to visual of the glyph (I think), and the commands clear the stack. So ignore this sub-sequence.
Next you will see a `170 77 112 93 15 74 226 78 cntrmask` sub-sequence. Ignore it.
Next is a `-127 -356 -95 560 rmoveto`.
Get -127 as dx1 and -356 as dy1 of the rmoveto command, `moves the current point to a position at the relative coordinates (dx1, dy1)`. In this time, the current-point points to (0, 0) and goes to (-127, -356). Then, clear the stack because rmoveto command clears.
Next is a `-13 37 -12 39 -7 31 -78 -20 rcurveline`.
Stroke the Bezier curve [s = (-127, -356), b0 = (-140, -319), b1 = (-152, -280), e = (-159, -249)] and stroke straight line (-159,-249) to (-237, -269). For now, the current-point points to (-237, -269).
Next, ... and so on.

So, how to interpret is like below;

```
index = 0
stack = new Stack
while charstring[index] != endchar
begin
  if charstring[index] is an Integer then
    stack.push(charstring[index])
  else
    run_command(charstring[index], stack)
  endif
  index++
end
```

Note 1. The first command of a charstring will be one of hstem, hstemhm, vstem, vstemhm, cntrmask, hintmask, rmoveto, hmoveto, or vmoveto. If the current command is one of that, the `w` part may be emitted at bottom of the stack at first time.
Note 2. Above program is very simplified one. The `callsubr`, `callgsubr`, and the `return` command may be been in a charstring and the above one will be not able to interpret the commands.
Note 3. The #5177 says `Every character path and subpath must begin with one of the moveto operators. If the current path is open when a moveto operator is encountered, the path is closed before performing the moveto operation`. So you will need to memorize the point that goes by latest moveto-like command.
Note 4. width of the glyph is calculated as below;

```
if w-part in the charstring then
  glyph_width = PrivateDICT.nominalWidthX + w
else
  glyph_width = PrivateDICT.defaultWidthX
endif
true_glyph_width = glyph_width * font_size_in_pixels * sqrt(det[TopDICT.FontMatrix])
```

Exempli gratia; If the glyph_width is 567 and font_size_in_pixels is 12 and TopDICT.FontMatrix is [0.001, 0, 0, 0.001, 0, 0], true_glyph_width = 567 \* 12 \* 0.001 = 6.804 in pixels.

**Comment by goldhillpaladin** [comment]
Thank you for your great answer. I'll try to code to do it. Maybe I need to read #5177 totally.

**Comment by pixie-grasper** [comment]
You are welcome.
works hard!頑張って!
